config/routes.rb
Rails.application.routes.draw do
  resources :setvs
 devise_for  :flightadmins, controllers: {
        registrations: 'sessions/registrations',
        sessions: 'sessions/sessions'
     }  
    devise_for :users, controllers: {
       registrations: 'users/registrations',
        sessions: 'users/sessions'
     }  
       devise_for :hoteladmins, controllers: {
         registrations: 'hoteladmins/registrations',
        sessions: 'hoteladmins/sessions'
     }  
          devise_for :admins, controllers: {
        registrations: 'admins/registrations',
        sessions: 'admins/sessions'
     }  

  resources :rates
  resources :timelines
      resources :profiles
     resources :avaibilities
     resources :bookings
     resources :bookingpage
    resources :hotels do
     resources :rooms
   end

  resources :rooms do
    resources :avaibilities 
    resources :bookings
  end


resources :booking
  resources :places
  resources :flights


    root to: 'site#home'

  get '/aboutus' => 'site#aboutus'
  get '/contactus' => 'site#contactus'
  get '/home' => 'site#home'
  get '/hotelprofile' => 'site#hotelprofile'
  get '/airlineprofile' => 'site#airlineprofile'
  get '/adminpage' => 'site#adminprofile'
  get '/userprofile' => 'profiles#userprofile'
  get '/memberprofile' => 'site#memberprofile'
  get '/partner' => 'site#partner'
  get '/booking' => 'site#bookingpage'
   get '/rewards' => 'site#discpoints'
 

   
   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/avaibility.rb
class Avaibility < ApplicationRecord
belongs_to :room


def self.search(search)
 where("pricepn > ?", "%#{search}%") 
end

end

app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :room
	belongs_to :hotel


end

app/models/flight.rb
class Flight < ApplicationRecord
end

app/models/flightadmin.rb
class Flightadmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/hotel.rb
class Hotel < ApplicationRecord
	has_many :rooms
	belongs_to :hoteladmin
	has_many :bookings
	has_many :rates

def self.search(search)
  where("location LIKE ?","%#{search}%") 
  # Hotel.joins(:rooms).where("location LIKE ?  AND roomtype LIKE ?", "%#{search}%","%#{search}%" )
end
 	




end

app/models/hoteladmin.rb
class Hoteladmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :hotels
        
end

app/models/place.rb
class Place < ApplicationRecord





	def self.search(search)
  where("location LIKE ?","%#{search}%") 
  # Hotel.joins(:rooms).where("location LIKE ?  AND roomtype LIKE ?", "%#{search}%","%#{search}%" )
end
 	

end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	  accepts_nested_attributes_for :user
end

app/models/rate.rb
class Rate < ApplicationRecord
	belongs_to :hotel
end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :hotel
	has_many :avaibilities
	has_many :bookings


def self.search(search)
 where("roomtype LIKE ?", "%#{search}%") 
end

end

app/models/setv.rb
class Setv < ApplicationRecord
end

app/models/timeline.rb
class Timeline < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

       
  has_one :profile
  has_many :rooms, through: :bookings
  has_many :bookings
   accepts_nested_attributes_for :profile
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_hoteladmin!
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show

     @room = Room.find(params[:room_id])
        profile = Profile.find_by_user_id(current_user.id)
     if @room.roomtype== "Single"
      profile.update_attributes(:rewardp => 0)
    end
  end

  # GET /rooms/new
  def new


    @hotel = Hotel.find_by_hoteladmin_id(current_hoteladmin.id)
    if @hotel.nil?
        redirect_to hotelprofile_path, notice: 'Add a hotel please.' 
      else
    @room = Room.find_by_hotel_id(@hotel.id)
    @room = Room.new
end

  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to hotelprofile_path, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to hotelprofile_path, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to hotelprofile_path, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:roomtype,:image, :romnum, :pricepn,:hotel_id,:quantity)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/setvs_helper.rb
module SetvsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/rooms/_form.html.erb
<%= form_for(room) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :hotel_id, :value => @hotel.id  %>
  </div>

  <div class="field">
   <label>Room Type</label>
    <%=f.select :roomtype, ['Single', 'Double', 'Triple', 'Family', 'Suite', 'VIP'], class: 'form-control'  %>
  </div>

<md-input-container >
  <div class="field">
    <label>Room Number</label>
    <%= f.number_field :romnum,  class: 'form-control' %>
  </div>
  </md-input-container>
  <md-input-container >
  <div class="field">
    <label>Room Image</label>
    <%= f.text_field :image,  class: 'form-control' %>
  </div>
  </md-input-container>

  <div class="actions">
    <%= f.submit "Add room" , class: "btn btn-default" %>
    <md-button class="md-accent md-raised md-hue-3" href="/hotelprofile">Back</md-button>
  </div>


<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<%if  hoteladmin_signed_in?%>

<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Roomtype</th>
      <th>Romnum</th>
      <th>Pricepn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.roomtype %></td>
        <td><%= room.romnum %></td>
        <td><%= room.pricepn %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>
<%else%>
<div class="alert alert-success" role="alert">
  <strong>You are not allowed to see this page</strong>
</div>
<%end%>

app/views/rooms/new.html.erb
<%if hoteladmin_signed_in?%>
<h1>New Room</h1>

<%= render 'form', room: @room%>

<%else%>
<div class="alert alert-success" role="alert">
  <strong>You are not allowed to see this page</strong>
</div>
<%end%>

app/views/rooms/show.html.erb
<h2>Thanks, you for your payment!</h2><md-button class="md-accent md-raised md-hue-3" href="/home">Back Home!</md-button>