config/routes.rb
Rails.application.routes.draw do
  resources :setvs
 devise_for  :flightadmins, controllers: {
        registrations: 'sessions/registrations',
        sessions: 'sessions/sessions'
     }  
    devise_for :users, controllers: {
       registrations: 'users/registrations',
        sessions: 'users/sessions'
     }  
       devise_for :hoteladmins, controllers: {
         registrations: 'hoteladmins/registrations',
        sessions: 'hoteladmins/sessions'
     }  
          devise_for :admins, controllers: {
        registrations: 'admins/registrations',
        sessions: 'admins/sessions'
     }  

  resources :rates
  resources :timelines
      resources :profiles
     resources :avaibilities
     resources :bookings
     resources :bookingpage
    resources :hotels do
     resources :rooms
   end

  resources :rooms do
    resources :avaibilities 
    resources :bookings
  end


resources :booking
  resources :places
  resources :flights


    root to: 'site#home'

  get '/aboutus' => 'site#aboutus'
  get '/contactus' => 'site#contactus'
  get '/home' => 'site#home'
  get '/hotelprofile' => 'site#hotelprofile'
  get '/airlineprofile' => 'site#airlineprofile'
  get '/adminpage' => 'site#adminprofile'
  get '/userprofile' => 'profiles#userprofile'
  get '/memberprofile' => 'site#memberprofile'
  get '/partner' => 'site#partner'
  get '/booking' => 'site#bookingpage'
   get '/rewards' => 'site#discpoints'
 

   
   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/avaibility.rb
class Avaibility < ApplicationRecord
belongs_to :room


def self.search(search)
 where("pricepn > ?", "%#{search}%") 
end

end

app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :room
	belongs_to :hotel


end

app/models/flight.rb
class Flight < ApplicationRecord
end

app/models/flightadmin.rb
class Flightadmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/hotel.rb
class Hotel < ApplicationRecord
	has_many :rooms
	belongs_to :hoteladmin
	has_many :bookings
	has_many :rates

def self.search(search)
  where("location LIKE ?","%#{search}%") 
  # Hotel.joins(:rooms).where("location LIKE ?  AND roomtype LIKE ?", "%#{search}%","%#{search}%" )
end
 	




end

app/models/hoteladmin.rb
class Hoteladmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :hotels
        
end

app/models/place.rb
class Place < ApplicationRecord





	def self.search(search)
  where("location LIKE ?","%#{search}%") 
  # Hotel.joins(:rooms).where("location LIKE ?  AND roomtype LIKE ?", "%#{search}%","%#{search}%" )
end
 	

end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	  accepts_nested_attributes_for :user
end

app/models/rate.rb
class Rate < ApplicationRecord
	belongs_to :hotel
end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :hotel
	has_many :avaibilities
	has_many :bookings


def self.search(search)
 where("roomtype LIKE ?", "%#{search}%") 
end

end

app/models/setv.rb
class Setv < ApplicationRecord
end

app/models/timeline.rb
class Timeline < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

       
  has_one :profile
  has_many :rooms, through: :bookings
  has_many :bookings
   accepts_nested_attributes_for :profile
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :authenticate_user!, :except => [:home, :aboutus, :adminprofile, :hotelprofile]
before_action :authenticate_admin!, :except => [:home, :aboutus,:contactus, :hotelprofile,:memberprofile, :bookingpage,:partner, :discpoints ]
before_action :authenticate_hoteladmin!, :except => [:home, :aboutus,:contactus, :memberprofile,:adminprofile, :bookingpage,:partner, :discpoints ]
  def home
     @hotels= Hotel.all
     @rooms =Room.all
     @avaibilities= Avaibility.all
     @bookings= Booking.all
  
  end

def discpoints
end
  def bookingpage


end


  def aboutus

  end

  def contactus
  end

  def hotelprofile
  @hotels=Hotel.all
  @rooms =Room.all
  @avaibilities= Avaibility.all
  @bookings= Booking.all
  end
  def airlineprofile
  end

  def adminprofile
    @bookings=Booking.all
      @users=Booking.all
        @hotels=Booking.all
@setvs=Setv.all
  end

  def partner
     
    # @amount=
   customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  # charge = Stripe::Charge.create(
  #   :customer    => customer.id,
  #   :amount      => @amount,
  #   :description => 'Rails Stripe customer',
  #   :currency    => 'usd'
  # )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to '/partner'
     # if room.roomtype== "Single"
      # profile.update_attributes(:rewardp => 0)
    # end


 end
 
 

  def memberprofile
    @hotels= Hotel.all
     @rooms =Room.all
     @avaibilities= Avaibility.all
    @profile = Profile.find_by_user_id(current_user.id)
      @hotels=Hotel.all
    @users= User.all


    if params[:search] 

    @hotels = Hotel.search(params[:search]).order("created_at DESC")
   else
    @hotels = Hotel.all.order("created_at DESC")
    
   end

   if params[:search]
    @places = Place.search(params[:search]).order("created_at DESC")
  else
    @Places = Place.all.order("created_at DESC")
  end

  #  if params[:search2]
  #   @avaibilities = Avaibility.search(params[:search2]).order("created_at DESC")
  # else
  #   @avaibilities = Avaibility.all.order("created_at DESC")
  # end
  end

end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/setvs_helper.rb
module SetvsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/aboutus.html.erb
<h1>Site#aboutus</h1>
<p>Find me in app/views/site/aboutus.html.erb</p>

app/views/site/airlineprofile.html.erb
<%= link_to('Logout', destroy_flightadmin_session_path, :method  => 'delete',  data: { confirm: 'Are you sure?' }) %> </li>

app/views/site/bookingpage.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>
<!-- pseduo algorithym taken 2 nigths cost 60Euros person = 3-->
<!-- 
 var roompricepn= 60; 
 people_number= 3
 percentage_earns= 13%
 total_booking_cst= (roompricepn*people_number) ("180")=(populate to transcation table)

 var triflex_earnings=  (total_booking_cst*percentage_earns)/(100);=(populate to transaction table) 

 var hotel_earnings= total_booking_cst -tripflex_earnings;(populate to transaction table) -->

app/views/site/discpoints.html.erb
<h2>Thanks, you for your payment with you points! </h2><md-button class="md-accent md-raised md-hue-3" href="/home">Back Home!</md-button>
<%@points=10000%>
   <%profile = Profile.find_by_user_id(current_user.id)%>
      


  <% profile.update_attributes(:rewardp => profile.rewardp-@points)%>

app/views/site/home.html.erb
  <%if !current_hoteladmin.nil?%>
  <%hotel = Hotel.find_by_hoteladmin_id(current_hoteladmin.id)%>
<%room = Room.find_by_hotel_id(hotel)%>
<%end%>

 <div class="panel panel-primary" style="height: 100%; width: 740px;">



<%= form_tag(memberprofile_path, :method => "get", id: "search-form") do %>

    <%= text_field_tag :search, params[:search], placeholder: "Type your Destination",  class: 'form-control' , require: 'true' %>


    <%= submit_tag "Search", :location => nil,  class: 'form-control'  %>

<% end %>



                <md-toolbar class="md-hue-2">
<div class="md-toolbar-tools">
 <h2 flex md-truncate>Most popular hotels</h2>
       </div>
</md-toolbar>
      <%totalB=0%>
         <%@hotels.each do |h|%>
         <%count=0%>
               <%@bookings.each do |b|%>
                      <% if b.hotel_id == h.id%>
                          <%count=count+1%>

                        <%end%>
                        <%totalB=totalB+1%>
                  <%end%>         

                 <%setv = Setv.find_by_id(1)%>
                         <%next if count<setv.set%>


                   
 <div flex-xs flex-gt-xs="100" layout="column" >
      <md-card md-theme="{{ showDarkTheme ? 'dark-orange' : 'default' }}" md-theme-watch>
        <md-card-title>
          <md-card-title-text>
            <span class="md-headline"><%=h.name%></span>

            <span class="md-subhead"><%=h.description%></span>
              

          </md-card-title-text>
          <md-card-title-media>
          <%if !h.hotelimg.nil?%>
            <div class="md-media-lg card-media"> <%= (image_tag h.hotelimg)%></div>
            <%else%>
            No image please set an image thanks
            <%end%>
       <br>
          </md-card-title-media>

          <md-card-title-media>
          <%if !h.hotelimg2.nil?%>
            <div class="md-media-lg card-media"> <%= (image_tag h.hotelimg2)%></div>
         <%else%>
            No image please set an image thanks
            <%end%>
          </md-card-title-media>
        </md-card-title>

        <% @rooms.each do |room| %>
            <%if room.hotel_id == h.id%>
               <%@avaibilities.each do |a|%>
                     <%if a.room_id ==room.id%>
                         <% if a.available==true%> 

                           <md-subheader class="md-primary"><%= room.roomtype %> Room Available   <md-button class="md-accent md-raised md-hue-3" href="/rooms/<%=room.id%>/bookings/new">Book Now!</md-button></md-subheader>

                           <%break%>
                          <%else%>
                            <md-subheader class="md-warn"> <%=room.roomtype%> rooms Sold out!</md-subheader>
                        <%end%>
                   <%end%>   
                <%end%> 
           <%end%> 
 <%end%>
            <md-card-actions layout="row" layout-align="end center">

       <md-subheader > This hotel has been booking <%=count%> times</md-subheader>
          <md-button class="md-accent md-raised md-hue-3"  href="/hotels/<%=h.id%>">See details</md-button>
        </md-card-actions>
      </md-card>

          
<%end%>

      </div>



      </div>
</div>





<script>
function isNumber(evt) {
    evt = (evt) ? evt : window.event;
    var charCode = (evt.which) ? evt.which : evt.keyCode;
    if (charCode > 31 && (charCode < 48 || charCode > 57)) {
        return false;
    }
    return true;
}
</script>

app/views/site/hotelprofile.html.erb
  <%if hoteladmin_signed_in?%>
<%hotel = Hotel.find_by_hoteladmin_id(current_hoteladmin.id)%>
<%room = Room.find_by_hotel_id(hotel)%>


  <%if hotel.nil? %>
<h3> You dont have a Hotel registred</h3>
<md-button href="/hotels/new" class="md-raised">Click here to add your Hotel</md-button>
<%else%> 
<%if current_hoteladmin.id== hotel.hoteladmin_id%>
<md-toolbar md-colors="::{background: '{{default}}-primary-700'}"  >
      <div class="md-toolbar-tools">
        <h2 flex md-truncate><%=hotel.name%> Hotel</h2>
      </div>
    </md-toolbar>
 <%= link_to 'Edit Hotel',  edit_hotel_path(hotel), class: "btn btn-default" %>
<%end%>

<%end%>

<%if room.nil? %>
<md-button class="md-accent md-raised md-hue-3" href="/rooms/new">Add rooms</md-button>
<%else%>

<div class="alert alert-success" role="alert" id="roomtT">
  You have  <strong><%=hotel.rooms.count%> Room</strong> available.
</div>

<md-button class="md-accent md-raised md-hue-3" ng-click="showAv();">See Avaibilities</md-button>
<md-button class="md-accent md-raised md-hue-3" href="/rooms/new">Add rooms</md-button>


<table class="table" id="roomT">
  <thead>
    <tr>
      <th>Room #</th>
      <th>Room Type</th>
      <th>Availablity</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>

<% @rooms.each do |room| %>
<%if hotel.id== room.hotel_id%>
    <tr>
      <th scope="row"><%= room.romnum%></th>
      <td><%= room.roomtype %></td>
      <td><%= link_to 'Set avaibility', new_room_avaibility_path(room), class: "btn btn-default" %>
      <%= link_to 'View avaibility',  room_avaibilities_path(room), class: "btn btn-default" %></td>
       <td><%= link_to 'Delete', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <%end%>
    <%end%>
  </tbody>
</table>

<div class="alert alert-success" role="alert" id="titleAv">
  <strong>All Availabilities</strong>
</div>
<table class="table" id="avaibilities">

  <thead>
    <tr>
      <th>Room #</th>
      <th>Available From</th>
      <th>To</th>
      <th>Price</th>
      <th>Avaibility</th>
    </tr>
  </thead>
  <tbody>
   <%(0..hotel.rooms.count).each do |i|%>
     <%@avaibilities.each do |h|%>
     <% if  hotel.rooms.ids[i] == h.room_id %>
            <%avaibility = Avaibility.find_by_room_id(hotel.rooms.ids[i])%>
            <%@var=h.id%>
            <% for avaibility in @avaibilities %>
            <% if  @var == avaibility.id %>
           <tr>
             <th scope="row"><%=avaibility.room.romnum%></th>
          
               <td> <%=avaibility.datef%></td>
                 <td> <%=avaibility.datet%></td>
             <td> <%=avaibility.pricepn%></td>
              <td> <%=avaibility.available%></td>
           </tr>
              <%end%>
              <%end%>
              <%end%>
              <%end%>
              <%end%>
          </tbody>
      </table>
      <md-button class="md-accent md-raised md-hue-3" ng-click="backAv()" id="back">Back</md-button>

<%end%>

<h1>Bookings</h1>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Made on</th>
      <th>Room Type</th>
      <th>By</th>
      <th> Total Paid</th>
      <th>Total earned</th>
    </tr>
  </thead>
  <tbody>
  <%@f=0%>
    <%if !hotel.nil?%>
    <%@bookings.each do |i|%>

       <%if i.hotel_id == hotel.id%>
   
 
    </tr>




    <tr>
      <th scope="row"><%=i.id%></th>
      <td><%=i.created_at%></td>
      <td><%=i.room.roomtype%></td>
      <%profile=Profile.find_by_user_id(i.user_id)%>
      <td> <%=profile.firstname%></td>

          <%@var=DateTime.parse(i.stdate)%>
         <%@var2=DateTime.parse(i.endate)%>
         <%if !@var.nil? and !@var2.nil? %>
         <%@c=@var2-@var%>
         <%end%>


            <%if !i.totalcost.nil?%>
              <%@p1=i.totalcost*@c%>
              <td><%=i.totalcost*@c%></td>
              <%@ti=@p1*10/100%>
              <%@earn=@p1-@ti%>
              <td><%=@earn%></td>
            <%end%>
          <%@f+=@earn%>

      
    </tr>
<%end%>
 <%end%>
  </tbody>
</table>

Total income: <%=@f%>
<%end%>

<%else%>
<div class="alert alert-success" role="alert">
  <strong>You are not allowed to see this page</strong>
</div>
<%end%>


<script type="text/javascript">
	$("#avaibilities").hide();
	$("#titleAv").hide();
	 $("#back").hide();
</script>

app/views/site/memberprofile.html.erb
  <% profile = Profile.find_by_user_id(current_user.id)%>
  <% if profile.nil?%>
<div class="alert">
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
  <strong>You cannot continue!</strong> Please create a profile
</div>
 <%= link_to('Create a profile ', new_profile_path(current_user.id), class: 'form-control') %></li>
  <%else%>

  <%if !current_hoteladmin.nil?%>
  <%hotel = Hotel.find_by_hoteladmin_id(current_hoteladmin.id)%>
<%room = Room.find_by_hotel_id(hotel)%>
<%end%>


<% if @hotels.blank? %>
<md-toolbar class="md-warn">
      <div class="md-toolbar-tools" >
<h2 flex md-truncate>Sorry <%=@profile.firstname%> There are no Hotels available in <%= params[:search] %>!!</h2>
     </div>
</md-toolbar>
<% else %>

<br>
<md-toolbar class="md-warn">
      <div class="md-toolbar-tools" >
<h2 flex md-truncate>Congratulations <%=@profile.firstname%> We found Hotels Available in <%= params[:search] %>!!</h2>
     </div>
</md-toolbar>

<%end%>
<%priceS=0%>
<%count=0%>
<%@hotels.each do |h|%>
     <%@rooms.each do |r|%>
        <% if r.hotel_id == h.id%>
             <%@avaibilities.each do |a|%>
                <%if a.room_id == r.id%>
                     <%priceS=priceS+ a.pricepn%>
                   
                  <%end%>
              <%end%>       
        <%end%>    
    <%end%> 
    <%count=count+1%>
<%end%>
<%if count>0%>
<div class="alert alert-success" role="alert">
  <strong>We suugest!</strong> you that have a budget of <%=(priceS/count)+100 %> per day to enjoy your trip in <%= params[:search] %>!
</div>
<md-button class="md-accent md-raised md-hue-3" ng-click="showH()">Book now</md-button>

<%end%>

<md-button class="md-accent md-raised md-hue-3" href="/home">Back</md-button>




<div id="hideH">
      
         <%@hotels.each do |h|%>
         
 <div flex-xs flex-gt-xs="100" layout="column" >
      <md-card md-theme="{{ showDarkTheme ? 'dark-orange' : 'default' }}" md-theme-watch>
        <md-card-title>
          <md-card-title-text>
            <span class="md-headline"><%=h.name%></span>
            <span class="md-subhead"><%=h.description%></span>
            <span><%= h.location %></span>
          </md-card-title-text>
          <md-card-title-media>
          <% if !h.hotelimg.nil?%>
            <div class="md-media-lg card-media"> <%= (image_tag h.hotelimg)%></div>
            <%else%>
            please add an image
            <%end%>
       <br>
          </md-card-title-media>
        </md-card-title>

        <% @rooms.each do |room| %>

            <% if room.hotel_id == h.id%>
                 
                 <%@avaibilities.each do |a| %>
                     <%if a.room_id == room.id%>
                          <%if a.available ==true%>
                             <td><%= room.roomtype %> Room</td>
                             <td> <strong>Available from: <%=a.datef%> To:  <%=a.datet%></strong></td>
                             <td> <strong>Price per night <%=a.pricepn%>€</strong> </td>
                             <%= link_to('Book now', new_room_booking_path(room.id), class: 'form-control')%>
                           <%end%>
                      <%end%>
                  <%end%>   
             <%else%>
         
              <%end%>
         <%end%>   
        <md-card-actions layout="row" layout-align="end center">
      
          <md-button>See details</md-button>
        </md-card-actions>
      </md-card>
      </div>












<%end%>







<h1>Places you can visit in <%= params[:search] %></h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Interest</th>
      <th>Price</th>
      <th>Open</th>
      <th>Close</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.location %></td>
        <td><%= place.interest %></td>
        <td><%= place.price %></td>
        <td><%= place.open %></td>
        <td><%= place.close %></td>
        <td><%= place.phone %></td>
    
      </tr>
    <% end %>
  </tbody>
</table>


</div>


<div id="hideR">


<h1>Rooms</h1>
<table>
  <thead>
    <tr>
      <th>Roomtype</th>
      <th>Romnum</th>
      <th>Pricepn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>


      <tr>
        <td><%= room.roomtype %></td>
        <td><%= room.romnum %></td>
        <td><%= room.pricepn %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>


<br>



















<%end%>
<script>
$("#hideR").hide();
$("#hideH").hide();
</script>

app/views/site/partner.html.erb
<h2>Thanks, you for your payment! </h2><md-button class="md-accent md-raised md-hue-3" href="/home">Back Home!</md-button>

app/views/site/userprofile.htlm.erb
  <%if user_signed_in?%>

  <%profile = Profile.find_by_user_id(current_user.id)%>

<%booking =Booking.find_by_user_id(current_user.id)%>


<h3> Welcome to your profile</h3>
<md-button href="/hotels/new" class="md-raised">Click here to add your Hotel</md-button>


  <

<md-toolbar md-colors="::{background: '{{default}}-primary-700'}"  >
      <div class="md-toolbar-tools">
        <h2 flex md-truncate><%=hotel.name%> Hotel</h2>
      </div>
    </md-toolbar>
 <%= link_to 'Edit Hotel',  edit_hotel_path(hotel), class: "btn btn-default" %>
<%end%>
<%end%>



<%if room.nil? %>
<md-button class="md-accent md-raised md-hue-3" href="/rooms/new">Add rooms</md-button>
<%else%>

<div class="alert alert-success" role="alert" id="roomtT">
  You have  <strong><%=hotel.rooms.count%> Room</strong> available.
</div>

<md-button class="md-accent md-raised md-hue-3" ng-click="showAv();">See Avaibilities</md-button>
<md-button class="md-accent md-raised md-hue-3" href="/rooms/new">Add rooms</md-button>


<table class="table" id="roomT">
  <thead>
    <tr>
      <th>Room #</th>
      <th>Room Type</th>
      <th>Availablity</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>

<% @rooms.each do |room| %>
<%if hotel.id== room.hotel_id%>
    <tr>
      <th scope="row"><%= room.romnum%></th>
      <td><%= room.roomtype %></td>
      <td><%= link_to 'Set avaibility', new_room_avaibility_path(room), class: "btn btn-default" %>
      <%= link_to 'View avaibility',  room_avaibilities_path(room), class: "btn btn-default" %></td>
       <td><%= link_to 'Delete', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <%end%>
    <%end%>
  </tbody>
</table>

<div class="alert alert-success" role="alert" id="titleAv">
  <strong>All Availabilities</strong>
</div>
<table class="table" id="avaibilities">

  <thead>
    <tr>
      <th>Room #</th>
      <th>Available From</th>
      <th>To</th>
      <th>Price</th>
      <th>Avaibility</th>
    </tr>
  </thead>
  <tbody>
   <%(0..hotel.rooms.count).each do |i|%>
     <%@avaibilities.each do |h|%>
     <% if  hotel.rooms.ids[i] == h.room_id %>
            <%avaibility = Avaibility.find_by_room_id(hotel.rooms.ids[i])%>
            <%@var=h.id%>
            <% for avaibility in @avaibilities %>
            <% if  @var == avaibility.id %>
           <tr>
             <th scope="row"><%=avaibility.room.romnum%></th>
          
               <td> <%=avaibility.datef%></td>
                 <td> <%=avaibility.datet%></td>
             <td> <%=avaibility.pricepn%></td>
              <td> <%=avaibility.available%></td>
           </tr>
              <%end%>
              <%end%>
              <%end%>
              <%end%>
              <%end%>
          </tbody>
      </table>
      <md-button class="md-accent md-raised md-hue-3" ng-click="backAv()" id="back">Back</md-button>

<%end%>
<%else%>
<div class="alert alert-success" role="alert">
  <strong>You are not allowed to see this page</strong>
</div>
<%end%>

<h1>Bookings</h1>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Date</th>
      <th>Room Type</th>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <%@bookings.each do |i|%>
       <%if i.hotel== current_hoteladmin.id%>

    <tr>
      <th scope="row">h.id</th>
      <td><%=i.created_at%></td>
      <td><%=i.room.roomtype%></td>
    
          <%profile=Profile.find_user_by_id(i.user_id)%>
      <td> <%=profile.firstname%></td>
      <%end%>
      
    </tr>
<%end%>
  </tbody>
</table>








<script type="text/javascript">
	$("#avaibilities").hide();
	$("#titleAv").hide();
	 $("#back").hide();
</script>