config/routes.rb
Rails.application.routes.draw do
  resources :setvs
 devise_for  :flightadmins, controllers: {
        registrations: 'sessions/registrations',
        sessions: 'sessions/sessions'
     }  
    devise_for :users, controllers: {
       registrations: 'users/registrations',
        sessions: 'users/sessions'
     }  
       devise_for :hoteladmins, controllers: {
         registrations: 'hoteladmins/registrations',
        sessions: 'hoteladmins/sessions'
     }  
          devise_for :admins, controllers: {
        registrations: 'admins/registrations',
        sessions: 'admins/sessions'
     }  

  resources :rates
  resources :timelines
      resources :profiles
     resources :avaibilities
     resources :bookings
     resources :bookingpage
    resources :hotels do
     resources :rooms
   end

  resources :rooms do
    resources :avaibilities 
    resources :bookings
  end


resources :booking
  resources :places
  resources :flights


    root to: 'site#home'

  get '/aboutus' => 'site#aboutus'
  get '/contactus' => 'site#contactus'
  get '/home' => 'site#home'
  get '/hotelprofile' => 'site#hotelprofile'
  get '/airlineprofile' => 'site#airlineprofile'
  get '/adminpage' => 'site#adminprofile'
  get '/userprofile' => 'profiles#userprofile'
  get '/memberprofile' => 'site#memberprofile'
  get '/partner' => 'site#partner'
  get '/booking' => 'site#bookingpage'
   get '/rewards' => 'site#discpoints'
 

   
   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/avaibility.rb
class Avaibility < ApplicationRecord
belongs_to :room


def self.search(search)
 where("pricepn > ?", "%#{search}%") 
end

end

app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :room
	belongs_to :hotel


end

app/models/flight.rb
class Flight < ApplicationRecord
end

app/models/flightadmin.rb
class Flightadmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/hotel.rb
class Hotel < ApplicationRecord
	has_many :rooms
	belongs_to :hoteladmin
	has_many :bookings
	has_many :rates

def self.search(search)
  where("location LIKE ?","%#{search}%") 
  # Hotel.joins(:rooms).where("location LIKE ?  AND roomtype LIKE ?", "%#{search}%","%#{search}%" )
end
 	




end

app/models/hoteladmin.rb
class Hoteladmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :hotels
        
end

app/models/place.rb
class Place < ApplicationRecord





	def self.search(search)
  where("location LIKE ?","%#{search}%") 
  # Hotel.joins(:rooms).where("location LIKE ?  AND roomtype LIKE ?", "%#{search}%","%#{search}%" )
end
 	

end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	  accepts_nested_attributes_for :user
end

app/models/rate.rb
class Rate < ApplicationRecord
	belongs_to :hotel
end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :hotel
	has_many :avaibilities
	has_many :bookings


def self.search(search)
 where("roomtype LIKE ?", "%#{search}%") 
end

end

app/models/setv.rb
class Setv < ApplicationRecord
end

app/models/timeline.rb
class Timeline < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

       
  has_one :profile
  has_many :rooms, through: :bookings
  has_many :bookings
   accepts_nested_attributes_for :profile
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
   before_action :authenticate_admin!
 
    before_action :set_timeline, only: [:show, :edit, :update, :destroy]

  # GET /timelines
  # GET /timelines.json
  def index
    @timelines = Timeline.all
  end

  # GET /timelines/1
  # GET /timelines/1.json
  def show
  end

  # GET /timelines/new
  def new
    @timeline = Timeline.new
  end

  # GET /timelines/1/edit
  def edit
  end

  # POST /timelines
  # POST /timelines.json
  def create
    @timeline = Timeline.new(timeline_params)

    respond_to do |format|
      if @timeline.save
        format.html { redirect_to adminpage_path, notice: 'Timeline was successfully created.' }
        format.json { render :show, status: :created, location: @timeline }
      else
        format.html { render :new }
        format.json { render json: @timeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timelines/1
  # PATCH/PUT /timelines/1.json
  def update
    respond_to do |format|
      if @timeline.update(timeline_params)
        format.html { redirect_to @timeline, notice: 'Timeline was successfully updated.' }
        format.json { render :show, status: :ok, location: @timeline }
      else
        format.html { render :edit }
        format.json { render json: @timeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timelines/1
  # DELETE /timelines/1.json
  def destroy
    @timeline.destroy
    respond_to do |format|
      format.html { redirect_to timelines_url, notice: 'Timeline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timeline
      @timeline = Timeline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timeline_params
      params.require(:timeline).permit(:title, :desc, :avatar)
    end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/setvs_helper.rb
module SetvsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/views/timelines/_form.html.erb
<%if admin_signed_in?%>

<%= form_for(timeline) do |f| %>
  <% if timeline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(timeline.errors.count, "error") %> prohibited this timeline from being saved:</h2>

      <ul>
      <% timeline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<md-input-container >

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control'%>
  </div>
</md-input-container>
<md-input-container >
  <div class="field">
    <%= f.label :desc %>
    <%= f.text_field :desc, class: 'form-control'%>
  </div>
</md-input-container>
<md-input-container >
  <div class="field">
    <label>Image</label>
    <%= f.text_field :avatar , class: 'form-control'%>
  </div>
</md-input-container>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>

<% end %>
<%else%>
<div class="alert alert-success" role="alert">
  <strong>You are not allowed to see this page</strong>
</div>
<%end%>

app/views/timelines/edit.html.erb
<%if admin_signed_in?%>

<h1>Editing Timeline</h1>

<%= render 'form', timeline: @timeline %>

<%= link_to 'Show', @timeline %> |
<%= link_to 'Back', timelines_path %>
<%else%>
<div class="alert alert-success" role="alert">
  <strong>You are not allowed to see this page</strong>
</div>
<%end%>

app/views/timelines/index.html.erb
<%if admin_signed_in?%>
   
<p id="notice"><%= notice %></p>

<h1>Timelines</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Desc</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timelines.each do |timeline| %>
      <tr>
        <td><%= timeline.title %></td>
        <td><%= timeline.desc %></td>
        <td><%= timeline.avatar %></td>
        <td><%= link_to 'Show', timeline %></td>
        <td><%= link_to 'Edit', edit_timeline_path(timeline) %></td>
        <td><%= link_to 'Destroy', timeline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timeline', new_timeline_path %>
<%else%>
<div class="alert alert-success" role="alert">
  <strong>You are not allowed to see this page</strong>
</div>
<%end%>

app/views/timelines/new.html.erb
<%if admin_signed_in?%>
   
<h1>New Timeline</h1>


<%= render 'form', timeline: @timeline %>

<%else%>
<div class="alert alert-success" role="alert">
  <strong>You are not allowed to see this page</strong>
</div>
<%end%>

app/views/timelines/show.html.erb
<%if admin_signed_in?%>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @timeline.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @timeline.desc %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @timeline.avatar %>
</p>

<%= link_to 'Edit', edit_timeline_path(@timeline) %> |
<%= link_to 'Back', timelines_path %>
<%else%>
<div class="alert alert-success" role="alert">
  <strong>You are not allowed to see this page</strong>
</div>
<%end%>