config/routes.rb
Rails.application.routes.draw do
  resources :setvs
 devise_for  :flightadmins, controllers: {
        registrations: 'sessions/registrations',
        sessions: 'sessions/sessions'
     }  
    devise_for :users, controllers: {
       registrations: 'users/registrations',
        sessions: 'users/sessions'
     }  
       devise_for :hoteladmins, controllers: {
         registrations: 'hoteladmins/registrations',
        sessions: 'hoteladmins/sessions'
     }  
          devise_for :admins, controllers: {
        registrations: 'admins/registrations',
        sessions: 'admins/sessions'
     }  

  resources :rates
  resources :timelines
      resources :profiles
     resources :avaibilities
     resources :bookings
     resources :bookingpage
    resources :hotels do
     resources :rooms
   end

  resources :rooms do
    resources :avaibilities 
    resources :bookings
  end


resources :booking
  resources :places
  resources :flights


    root to: 'site#home'

  get '/aboutus' => 'site#aboutus'
  get '/contactus' => 'site#contactus'
  get '/home' => 'site#home'
  get '/hotelprofile' => 'site#hotelprofile'
  get '/airlineprofile' => 'site#airlineprofile'
  get '/adminpage' => 'site#adminprofile'
  get '/userprofile' => 'profiles#userprofile'
  get '/memberprofile' => 'site#memberprofile'
  get '/partner' => 'site#partner'
  get '/booking' => 'site#bookingpage'
   get '/rewards' => 'site#discpoints'
 

   
   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/avaibility.rb
class Avaibility < ApplicationRecord
belongs_to :room


def self.search(search)
 where("pricepn > ?", "%#{search}%") 
end

end

app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :room
	belongs_to :hotel


end

app/models/flight.rb
class Flight < ApplicationRecord
end

app/models/flightadmin.rb
class Flightadmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/hotel.rb
class Hotel < ApplicationRecord
	has_many :rooms
	belongs_to :hoteladmin
	has_many :bookings
	has_many :rates

def self.search(search)
  where("location LIKE ?","%#{search}%") 
  # Hotel.joins(:rooms).where("location LIKE ?  AND roomtype LIKE ?", "%#{search}%","%#{search}%" )
end
 	




end

app/models/hoteladmin.rb
class Hoteladmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :hotels
        
end

app/models/place.rb
class Place < ApplicationRecord





	def self.search(search)
  where("location LIKE ?","%#{search}%") 
  # Hotel.joins(:rooms).where("location LIKE ?  AND roomtype LIKE ?", "%#{search}%","%#{search}%" )
end
 	

end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	  accepts_nested_attributes_for :user
end

app/models/rate.rb
class Rate < ApplicationRecord
	belongs_to :hotel
end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :hotel
	has_many :avaibilities
	has_many :bookings


def self.search(search)
 where("roomtype LIKE ?", "%#{search}%") 
end

end

app/models/setv.rb
class Setv < ApplicationRecord
end

app/models/timeline.rb
class Timeline < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

       
  has_one :profile
  has_many :rooms, through: :bookings
  has_many :bookings
   accepts_nested_attributes_for :profile
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to adminpage_path, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :location, :interest, :price, :open, :close, :phone)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/setvs_helper.rb
module SetvsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/places/_form.html.erb
<%= form_for(place) do |f| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">

    <%= f.hidden_field :interest %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :open %>
    <%= f.datetime_select :open %>
  </div>

  <div class="field">
    <%= f.label :close %>
    <%= f.datetime_select :close %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Interest</th>
      <th>Price</th>
      <th>Open</th>
      <th>Close</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.location %></td>
        <td><%= place.interest %></td>
        <td><%= place.price %></td>
        <td><%= place.open %></td>
        <td><%= place.close %></td>
        <td><%= place.phone %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @place.location %>
</p>

<p>
  <strong>Interest:</strong>
  <%= @place.interest %>
</p>

<p>
  <strong>Price:</strong>
  <%= @place.price %>
</p>

<p>
  <strong>Open:</strong>
  <%= @place.open %>
</p>

<p>
  <strong>Close:</strong>
  <%= @place.close %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @place.phone %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>